### ISSUE TITLE
Load Zivid two .yaml setting

### ISSUE THREAD

**Issue by HM102** [zivid/zivid-halcon-samples#46]
How can I load the .yaml camera setting file saved from zividStudio in halcon. I know it should be first converted to .json, but how can I loaded after wards.

**Comment by SatjaSivcev** [comment]
I believe this is what you are looking for:
https://github.com/zivid/zivid-halcon-samples/blob/master/source/hdev/Camera/Basic/CaptureHDRLoop.hdev#L52
